package org.mepcity.kursplatform.iam.domain;

public enum OperationCode {
    PROVIDER_TOKEN_EXCHANGE,
    PLATFORM_ADMIN_ACTIVATE,
    CONTEXT_ACTIVATE,
    SESSION_REFRESH,
    SESSION_LOGOUT,
    DEVICE_LIST,
    DEVICE_SELF_REVOKE,
    DEVICE_SESSION_REVOKE,
    PLATFORM_DEVICE_REVOKE,
    USER_DISABLE,
    USER_LOGOUT,
    PASSWORD_RESET,
    TEACHER_ACCOUNT_CREATE,
    TEACHER_ACCOUNT_FINALIZE,
    PROVIDER_COMMAND_CLAIM,
    EVENT_CURSOR_ADVANCE,
    SESSION_INFO,
    CONTEXT_SELECTION_LIST
}
